name: RepoLab Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Artifact
        run: |
          mkdir output
          echo "RepoLab Works 🎉" > output/result.txt

      - uses: actions/upload-artifact@v4
        with:
          name: RepoLab-Artifact
          path: output/