name: RepoLab Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Website
        run: |
          mkdir output
          cat > output/index.html <<EOF
          <html>
          <head>
          <style>
          body{
            background:#111;
            color:#fff;
            font-family:sans-serif;
            text-align:center;
            padding-top:80px;
          }
          h1{font-size:48px;}
          p{font-size:22px;color:#aaa;}
          </style>
          </head>
          <body>
            <h1>RepoLab Works 🎉</h1>
            <p>GitHub is under control now.</p>
          </body>
          </html>
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: RepoLab-Site
          path: output/